version: "3.8"

services:
  localstack:
    container_name: "Onboarding_local_stack"
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      # - DATA_DIR=${DATA_DIR-}
      - SERVICES=dynamodb
      - PERSISTENCE=1
    volumes:
      # - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - onboarding:/home/node/app
    command: sh -cx "aws dynamodb create-table  --attribute-definitions AttributeName=Test,AttributeType=S --table-name OnboardingTest --key-schema AttributeName=Test,KeyType=HASH --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5 --endpoint-url http://localhost:4566"
    # command: echo "hello"
volumes:
  onboarding: